```{r, include = FALSE}
library(pracma)
```

# P2 (a)

```{r}
# primal symmetric form

library(lpSolve)

f.obj <- c(2, -1, -2)

f.con <- matrix(c(-3,-1,-4,
                  -2,-1,-1),
                nrow = 2, byrow = TRUE)

f.dir <- c(">=",">=")

f.rhs <- c(-6,-3)

result <- lp("min", f.obj, f.con, f.dir, f.rhs)
print(result)
soln <- result$solution
print(soln)
```
# P2 (c)
```{r}
# dual symmetric form

f.obj <- c(-6,-3)

f.con <- matrix(c(-3,-2,
                  -1,-1,
                  -4,-1),
                nrow = 3, byrow = TRUE)

f.dir <- c("<=","<=","<=")

f.rhs <- c(2,-1,-2)

result <- lp("max", f.obj, f.con, f.dir, f.rhs)
print(result)
soln <- result$solution
print(soln)
```

```{r, include = FALSE}
library(pracma)
```

# P3 (a)

```{r}
A <- matrix(c(3, 1, 4, 2, 1, 1), 2, 3, byrow = TRUE)
A
rref(A)

Ab <- matrix(c(3, 1, 4, 2, 2, 1, 1, 1), 2, 4, byrow = TRUE)
Ab
rref(Ab)

a1 <- c(3,2)
a2 <- c(1,1)
a3 <- c(4,1)
b <- c(2,1)

# choose different pairs of linearly independent 
# columns to be first two in A to find all basic solns
rref(cbind(a1,a2,b))
rref(cbind(a1,a3,b))
rref(cbind(a2,a3,b))

```
# P3 (b)
```{r}
# Primal solution with the asymmetric form

f.obj <- c(5,3,5)

f.con <- matrix(c(3,1,4,
                  2,1,1),
                nrow = 2, byrow = TRUE)

f.dir <- c("=","=")

f.rhs <- c(2,1)

result <- lp("min", f.obj, f.con, f.dir, f.rhs)
print(result)
soln <- result$solution
print(soln)

optimalvalue <- result$objval

print(optimalvalue)

```

# P4 

```{r}
library(lpSolve)

# Set coefficients of the objective function
f.obj <- c(-11,-16,-15,-5,0,0,0)

# Set matrix corresponding to coefficients of constraints by rows
# Assumes non-negative solutions
# nA nB nC nD n1 n2 n3
f.con <- matrix(c(6,12,9,1,1,0,0,
                  4,4,6,1,0,1,0,
                  3,2,3,2,0,0,1),
                nrow = 3, byrow = TRUE)

# Set inequality signs
f.dir <- c("=","=","=")

# Set right hand side coefficients
f.rhs <- c(324000, 124200, 64800)

# Solution to linear program
result <- lp("min", f.obj, f.con, f.dir, f.rhs, compute.sens = T)

primalsoln <- result$solution
print("    nA      nB          nC      nD           n1      n2          n3")
primalsoln
optimalvalue <- result$objval
print("The optimal value of the objective function is ... ")
optimalvalue
```
