---
title: "Homework 3  - Maqth 294"
author: "Dhyey Mavani"
date: "date"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5

---

### Dhyey Mavani      


```{r, include = FALSE}
library(pracma)
```

```{r}
A <- matrix(c(1, 2, 1, 2, 1, 1), 2, 3, byrow = TRUE)
A
rref(A)

Ab <- matrix(c(1, 2, 1, 3, 2, 1, 1, 2), 2, 4, byrow = TRUE)
Ab
rref(Ab)

a1 <- c(1,2)
a2 <- c(2,1)
a3 <- c(1,1)
b <- c(3,2)

# choose different pairs of linearly independent 
# columns to be first two in A to find all basic solns
rref(cbind(a1,a2,b))
rref(cbind(a1,a3,b))
rref(cbind(a2,a3,b))

```

```{r}
# Primal solution with the asymmetric form

library(lpSolve)

f.obj <- c(1,2,1)

f.con <- matrix(c(1,2,1,
                  2,1,1),
                nrow = 2, byrow = TRUE)

f.dir <- c("=","=")

f.rhs <- c(3,2)

result <- lp("min", f.obj, f.con, f.dir, f.rhs)
print(result)
soln <- result$solution
print(soln)

optimalvalue <- result$objval

print(optimalvalue)


```

```{r}
# Complementary slackness example

# Set coefficients of the objective function
f.obj <- c(-12,-9,-7)

# Set matrix corresponding to coefficients of constraints by rows
# Assumes non-negative solutions
f.con <- matrix(c(5,1,3,
                  3,1,0),
                nrow = 2, byrow = TRUE)

# Set inequality signs
f.dir <- c("=","=")

# Set right hand side coefficients
f.rhs <- c(5,1)

# Solution to linear program
result <- lp("min", f.obj, f.con, f.dir, f.rhs, compute.sens = T)

primalsoln <- result$solution # x1 x2 x3

optimalvalue <- result$objval

# Given the primal solution, we can construct the dual solution
# using complementary slackness: solve 5*y1+3*y2=13, 3*y1=6 to get
# y1=2, y2=1. Check this result:

dualsoln <- result$duals[1:2] # y1 y2

# changing b=f.rhs should change optimal value by y1*delta_b1+y2*delta_b2
delta_b <- c(2,2)
f.rhs <- c(3,2)+delta_b
change <- lp("min", f.obj, f.con, f.dir, f.rhs)$objval - optimalvalue
dualsoln[1]*delta_b[1]+dualsoln[2]*delta_b[2]
```
