---
title: "Dhyey Mavani Code for ECON-361 Final Empirical Project"
author: "Dhyey Mavani"
date: "15 December 2022"
output:
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r data-wrangling}
data <- read.csv(file = 'imported_data.csv')
colnames(data) <- c("year", "year_code", "country_name", "country_code", 
                    "pct_GDP_val_add_by_serv", "pct_urban_popl",
                    "pct_GDP_govt_exp_on_edu")
data <- subset(data, select = -c(year_code,country_name))
data$year <- as.numeric(data$year)
data$pct_GDP_govt_exp_on_edu <- as.numeric(data$pct_GDP_govt_exp_on_edu)
data$pct_GDP_val_add_by_serv <- as.numeric(data$pct_GDP_val_add_by_serv)
data$country_code[data$country_code == c("AUS","AUT","BEL","CAN","CHL","CZE",
                                         "DNK","EST","FIN","FRA","DEU","GRC",
                                         "HUN","ISL","IRL","ISR","ITA","JPN",
                                         "KOR","LVA","LTU","LUX","MEX","NLD",
                                         "NZL","NOR","POL","PRT","SVK","SVN",
                                         "ESP","SWE","CHE","TUR","GBR","USA")] <- 
  c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,
     19,20,21,22,23,24,25,26,27,28,29,30,31,31,33,34,35,36)
data$country_code <- as.numeric(data$country_code)
data <- tidyr::drop_na(data)
write.csv(data, file = "dhyey_cleaned_data.csv")
```

```{r}
cleaned_data <- read.csv(file = "dhyey_cleaned_data.csv")
# install.packages("ivreg")
library("ivreg")
iv1 <- ivreg(pct_urban_popl ~ pct_GDP_val_add_by_serv | pct_GDP_govt_exp_on_edu, data = cleaned_data)
summary(iv1)
```

```{r}
naive_ols <- lm(pct_urban_popl ~ pct_GDP_val_add_by_serv, data = cleaned_data)
summary(naive_ols)
```

```{r}
stage1 <- lm(pct_GDP_val_add_by_serv ~ pct_GDP_govt_exp_on_edu, data = cleaned_data)
summary(stage1)

cleaned_data[["pred_pct_GDP_val_add_by_serv"]] <- predict(stage1, cleaned_data)
stage2 <- lm(pct_urban_popl ~ pred_pct_GDP_val_add_by_serv, data = cleaned_data)
summary(stage2)
```

