---
output:
  pdf_document: default
  html_document: default
---
```{r}
# install.packages("readxl")
library(readxl)

data <- read_excel("CAPM-DATA-1.xlsx")

data
```

```{r}
data <- as.matrix(data)
risk_free_asset = data[,6]
excess_returns = data[,1:5] - risk_free_asset
market_excess_returns = excess_returns[,5]
stocks_excess_returns = excess_returns[,1:4]
```

```{r (a) and (b)}
# for (a) we can look at the coefficients of the explanatory variable
# for (b) we cna look at the coefficients and stats of the intercept
lm_1 <- lm(stocks_excess_returns[,1] ~ market_excess_returns)
summary(lm_1)
lm_2 <- lm(stocks_excess_returns[,2] ~ market_excess_returns)
summary(lm_2)
lm_3 <- lm(stocks_excess_returns[,3] ~ market_excess_returns)
summary(lm_3)
lm_4 <- lm(stocks_excess_returns[,4] ~ market_excess_returns)
summary(lm_4)
```

```{r (c)}
confint(lm_1, level = 0.95)
confint(lm_2, level = 0.95)
confint(lm_3, level = 0.95)
confint(lm_4, level = 0.95)
```

```{r (d)}
# Compute the t-statistic
t_stat <- (coef(lm_1)["market_excess_returns"] - 1) / summary(lm_1)$coef["market_excess_returns", "Std. Error"]

# Obtain the p-value associated with the t-statistic
p_value <- 2 * (1 - pt(abs(t_stat), 2))
p_value
# Compare p-value to chosen level of significance (e.g., 0.05)
if (p_value < 0.05) {
  cat("Reject null hypothesis: slope coefficient is not equal to 1\n")
} else {
  cat("Fail to reject null hypothesis: slope coefficient is equal to 1\n")
}

# Compute the t-statistic
t_stat <- (coef(lm_2)["market_excess_returns"] - 1) / summary(lm_2)$coef["market_excess_returns", "Std. Error"]

# Obtain the p-value associated with the t-statistic
p_value <- 2 * (1 - pt(abs(t_stat), 2))
p_value
# Compare p-value to chosen level of significance (e.g., 0.05)
if (p_value < 0.05) {
  cat("Reject null hypothesis: slope coefficient is not equal to 1\n")
} else {
  cat("Fail to reject null hypothesis: slope coefficient is equal to 1\n")
}

# Compute the t-statistic
t_stat <- (coef(lm_3)["market_excess_returns"] - 1) / summary(lm_3)$coef["market_excess_returns", "Std. Error"]

# Obtain the p-value associated with the t-statistic
p_value <- 2 * (1 - pt(abs(t_stat), 2))
p_value
# Compare p-value to chosen level of significance (e.g., 0.05)
if (p_value < 0.05) {
  cat("Reject null hypothesis: slope coefficient is not equal to 1\n")
} else {
  cat("Fail to reject null hypothesis: slope coefficient is equal to 1\n")
}

# Compute the t-statistic
t_stat <- (coef(lm_4)["market_excess_returns"] - 1) / summary(lm_4)$coef["market_excess_returns", "Std. Error"]

# Obtain the p-value associated with the t-statistic
p_value <- 2 * (1 - pt(abs(t_stat), 2))
p_value
# Compare p-value to chosen level of significance (e.g., 0.05)
if (p_value < 0.05) {
  cat("Reject null hypothesis: slope coefficient is not equal to 1\n")
} else {
  cat("Fail to reject null hypothesis: slope coefficient is equal to 1\n")
}

```

```{r (e)}
# One sided test for Microsoft
# Compute the t-statistic
t_stat <- (coef(lm_1)["market_excess_returns"] - 1) / summary(lm_1)$coef["market_excess_returns", "Std. Error"]

# Obtain the p-value associated with the t-statistic
p_value <- (1 - pt(abs(t_stat), 2))
p_value
# Compare p-value to chosen level of significance (e.g., 0.05)
if (p_value < 0.05) {
  cat("Reject null hypothesis: slope coefficient is not equal to 1\n")
} else {
  cat("Fail to reject null hypothesis: slope coefficient is equal to 1\n")
}
```

```{r}
lm_1 <- lm(stocks_excess_returns[,1] ~ market_excess_returns)

summary(lm_1)

coef <- summary(lm_1)$coefficients["market_excess_returns", "Estimate"]
coef
std_err <- summary(lm_1)$coefficients["market_excess_returns", "Std. Error"]
std_err
df <- 118
t_stat <- (coef - 1) / std_err
p_value <- 2 * pt(abs(t_stat), df, lower.tail = FALSE)

alpha <- 0.05
t_crit <- qt(alpha / 2, df, lower.tail = FALSE)

if (abs(t_stat) > t_crit) {
  cat("Reject the null hypothesis that the coefficient of market_excess_returns is equal to 1.")
} else {
  cat("Cannot reject the null hypothesis that the coefficient of market_excess_returns is equal to 1.")
}

cat("\n")
cat("t-statistic:", t_stat, "\n")
cat("p-value:", p_value, "\n")
cat("critical t-value:", t_crit, "\n")

```

```{r}
lm_2 <- lm(stocks_excess_returns[,2] ~ market_excess_returns)

summary(lm_2)

coef <- summary(lm_2)$coefficients["market_excess_returns", "Estimate"]
coef
std_err <- summary(lm_2)$coefficients["market_excess_returns", "Std. Error"]
std_err
df <- 118
t_stat <- (coef - 1) / std_err
p_value <- 2 * pt(abs(t_stat), df, lower.tail = FALSE)

alpha <- 0.05
t_crit <- qt(alpha / 2, df, lower.tail = FALSE)

if (abs(t_stat) > t_crit) {
  cat("Reject the null hypothesis that the coefficient of market_excess_returns is equal to 1.")
} else {
  cat("Cannot reject the null hypothesis that the coefficient of market_excess_returns is equal to 1.")
}

cat("\n")
cat("t-statistic:", t_stat, "\n")
cat("p-value:", p_value, "\n")
cat("critical t-value:", t_crit, "\n")

```

```{r}
lm_3 <- lm(stocks_excess_returns[,3] ~ market_excess_returns)

summary(lm_3)

coef <- summary(lm_3)$coefficients["market_excess_returns", "Estimate"]
coef
std_err <- summary(lm_3)$coefficients["market_excess_returns", "Std. Error"]
std_err
df <- 118
t_stat <- (coef - 1) / std_err
p_value <- 2 * pt(abs(t_stat), df, lower.tail = FALSE)

alpha <- 0.05
t_crit <- qt(alpha / 2, df, lower.tail = FALSE)

if (abs(t_stat) > t_crit) {
  cat("Reject the null hypothesis that the coefficient of market_excess_returns is equal to 1.")
} else {
  cat("Cannot reject the null hypothesis that the coefficient of market_excess_returns is equal to 1.")
}

cat("\n")
cat("t-statistic:", t_stat, "\n")
cat("p-value:", p_value, "\n")
cat("critical t-value:", t_crit, "\n")

```

```{r}
lm_4 <- lm(stocks_excess_returns[,4] ~ market_excess_returns)

summary(lm_4)

coef <- summary(lm_4)$coefficients["market_excess_returns", "Estimate"]
coef
std_err <- summary(lm_4)$coefficients["market_excess_returns", "Std. Error"]
std_err
df <- 118
t_stat <- (coef - 1) / std_err
p_value <- 2 * pt(abs(t_stat), df, lower.tail = FALSE)

alpha <- 0.05
t_crit <- qt(alpha / 2, df, lower.tail = FALSE)

if (abs(t_stat) > t_crit) {
  cat("Reject the null hypothesis that the coefficient of market_excess_returns is equal to 1.")
} else {
  cat("Cannot reject the null hypothesis that the coefficient of market_excess_returns is equal to 1.")
}

cat("\n")
cat("t-statistic:", t_stat, "\n")
cat("p-value:", p_value, "\n")
cat("critical t-value:", t_crit, "\n")

```